### ISSUE TITLE
Wrong board picture

### ISSUE THREAD

**Issue by T00ManySecrets** [XyleMora/EBAZ4205#4]
I have the exact miner but my board does not look like this. I'm missing the sd card slot, JTAG and UART pins.

**Comment by XyleMora** [comment]
When buying board from Aliexpress you can select one with soldered SD card slot and JTAG, UART pins. Or you can solder them by yourself. I think that these peripherals are very helpful if your are using EBAZ4205 as Xilinx Zynq development board.

**Comment by T00ManySecrets** [comment]
> When buying board from Aliexpress you can select one with soldered SD card slot and JTAG, UART pins. Or you can solder them by yourself. I think that these peripherals are very helpful if your are using EBAZ4205 as Xilinx Zynq development board.

Thank you man. You helped a lot.
