### ISSUE TITLE
pinout_io.png pin numbering 10 is wrong

### ISSUE THREAD

**Issue by meteowrite** [XyleMora/EBAZ4205#5]
Hi,

seems there is a typo on the numbering of pin positions in the [pinout_io.png](https://github.com/XyleMora/EBAZ4205/blob/main/Documents/Pinout/pinout_io.png). IMO, top-left pin number **10** should be **19**.

**Comment by botnursery** [comment]
![pinout_data1-3](https://user-images.githubusercontent.com/54031418/224133545-111e6e85-5fbf-420f-9f03-c93700ed468d.png)
